# Generated by Django 4.2.5 on 2023-10-11 13:46

from django.conf import settings
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ConnectionTool',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='Customer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('company_name', models.CharField(max_length=200)),
                ('phone_number', models.CharField(max_length=16, unique=True, validators=[django.core.validators.RegexValidator(message="Phone number must be entered in the format: '+905551234567'. Up to 15 digits allowed.", regex='^\\+?1?\\d{9,15}$')])),
                ('credit_amount', models.IntegerField(default=0)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='DtcInfo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=7, unique=True)),
                ('desc', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Ecu',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('number', models.CharField(max_length=15)),
            ],
        ),
        migrations.CreateModel(
            name='EcuBrand',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='Employee',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='FileProcess',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='FileRequest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('file_type', models.CharField(choices=[('E', 'ECU file'), ('T', 'Transmission File')], max_length=1)),
                ('transmissin', models.CharField(choices=[('A', 'AUTO'), ('M', 'MANUAL')], max_length=1)),
                ('tool_type', models.CharField(choices=[('S', 'Slave'), ('M', 'Master')], max_length=1)),
                ('customer_description', models.TextField(max_length=400)),
                ('total_price', models.IntegerField()),
                ('original_file', models.FileField(upload_to='uploads/original/')),
                ('employee_description', models.TextField(blank=True, max_length=400, null=True)),
                ('processed_file', models.FileField(blank=True, null=True, upload_to='uploads/processed/')),
                ('customer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='database.customer')),
                ('ecu', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='database.ecu')),
                ('employee', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='database.employee')),
            ],
        ),
        migrations.CreateModel(
            name='FileSale',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=60, unique=True)),
                ('file', models.FileField(unique=True, upload_to='uploads/for_sale/')),
                ('desc', models.TextField(max_length=400)),
                ('price', models.IntegerField()),
                ('owners', models.ManyToManyField(to='database.customer')),
            ],
        ),
        migrations.CreateModel(
            name='Knowledge',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100, unique=True)),
                ('link', models.URLField(blank=True, null=True)),
                ('link_title', models.CharField(blank=True, max_length=60, null=True)),
                ('desc', models.TextField(blank=True, max_length=600, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Vehicle',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('year', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='VehicleBrand',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='VehicleCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='VehicleModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('brand', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='database.vehiclebrand')),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='database.vehiclecategory')),
            ],
        ),
        migrations.CreateModel(
            name='VehicleEngine',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('hp', models.IntegerField()),
                ('fuel_type', models.CharField(choices=[('P', 'Petrol'), ('D', 'Diesel')], max_length=1)),
                ('vehicle', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='database.vehicle')),
            ],
        ),
        migrations.AddField(
            model_name='vehicle',
            name='model',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='database.vehiclemodel'),
        ),
        migrations.CreateModel(
            name='Transaction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('category', models.CharField(choices=[('E', 'Expense'), ('D', 'Deposit')], max_length=1)),
                ('amount', models.IntegerField()),
                ('customer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='database.customer')),
                ('file_bought', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='database.filesale')),
                ('file_request', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='database.filerequest')),
            ],
        ),
        migrations.CreateModel(
            name='ProcessPricing',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('price', models.IntegerField()),
                ('process', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='database.fileprocess')),
                ('vehicle', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='database.vehicle')),
            ],
        ),
        migrations.CreateModel(
            name='KnowledgePart',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('knowledge', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='database.knowledge')),
            ],
        ),
        migrations.CreateModel(
            name='KnowledgeBullet',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('content', models.CharField(max_length=100)),
                ('part', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='database.knowledgepart')),
            ],
        ),
        migrations.AddField(
            model_name='filesale',
            name='vehicle',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='database.vehicle'),
        ),
        migrations.AddField(
            model_name='filerequest',
            name='engine',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='database.vehicleengine'),
        ),
        migrations.AddField(
            model_name='filerequest',
            name='processes',
            field=models.ManyToManyField(to='database.fileprocess'),
        ),
        migrations.AddField(
            model_name='filerequest',
            name='tool',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='database.connectiontool'),
        ),
        migrations.AddField(
            model_name='filerequest',
            name='vehicle',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='database.vehicle'),
        ),
        migrations.CreateModel(
            name='EcuModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('brand', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='database.ecubrand')),
            ],
        ),
        migrations.AddField(
            model_name='ecu',
            name='model',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='database.ecumodel'),
        ),
        migrations.AddField(
            model_name='ecu',
            name='vehicles',
            field=models.ManyToManyField(to='database.vehicle'),
        ),
        migrations.AddConstraint(
            model_name='vehiclemodel',
            constraint=models.UniqueConstraint(fields=('brand', 'name'), name='vehiclemodel_brand_name_unique_constraint'),
        ),
        migrations.AddConstraint(
            model_name='vehicleengine',
            constraint=models.UniqueConstraint(fields=('vehicle', 'name', 'hp'), name='vehicleengine_vehicle_name_hp_unique_constraint'),
        ),
        migrations.AddConstraint(
            model_name='vehicle',
            constraint=models.UniqueConstraint(fields=('model', 'year'), name='vehicle_model_year_constraint'),
        ),
        migrations.AddConstraint(
            model_name='processpricing',
            constraint=models.UniqueConstraint(fields=('vehicle', 'process'), name='processpricing_process_vehicle_unique_constraint'),
        ),
        migrations.AddConstraint(
            model_name='knowledgepart',
            constraint=models.UniqueConstraint(fields=('title', 'knowledge'), name='knowledgepart_title_knowledge_unique_constraint'),
        ),
        migrations.AddConstraint(
            model_name='knowledgebullet',
            constraint=models.UniqueConstraint(fields=('content', 'part'), name='knowledgebullet_content_part_unique_constraint'),
        ),
        migrations.AddConstraint(
            model_name='ecumodel',
            constraint=models.UniqueConstraint(fields=('name', 'brand'), name='ecumodel_name_brand_unique_constraint'),
        ),
        migrations.AddConstraint(
            model_name='ecu',
            constraint=models.UniqueConstraint(fields=('model', 'number'), name='ecu_model_number_unique_constraint'),
        ),
    ]
