# Generated by Django 4.2.5 on 2023-10-11 14:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('database', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ecu',
            name='vehicles',
            field=models.ManyToManyField(blank=True, to='database.vehicle'),
        ),
        migrations.AlterField(
            model_name='filesale',
            name='owners',
            field=models.ManyToManyField(blank=True, to='database.customer'),
        ),
    ]
