# Generated by Django 4.2.5 on 2023-10-27 13:27

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('database', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='vehicle',
            name='potential',
        ),
        migrations.AddField(
            model_name='vehiclepotential',
            name='vehicle',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='database.vehicle'),
            preserve_default=False,
        ),
    ]
