# Generated by Django 4.2.5 on 2023-10-27 13:29

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('database', '0002_remove_vehicle_potential_vehiclepotential_vehicle'),
    ]

    operations = [
        migrations.AlterField(
            model_name='vehiclepotential',
            name='vehicle',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='database.vehicle'),
        ),
    ]
