# Generated by Django 4.2.5 on 2023-10-30 17:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('database', '0004_remove_processpricing_price_customer_pricing_class_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='systemsetting',
            name='bank_account_owner_name',
            field=models.CharField(default='Mehmet Urfi Yazıcı', max_length=100),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='systemsetting',
            name='bank_name',
            field=models.CharField(default='Türkiye İş Bankası A.Ş.', max_length=200),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='systemsetting',
            name='credit_eur_price',
            field=models.FloatField(default=1),
        ),
        migrations.AddField(
            model_name='systemsetting',
            name='credit_try_price',
            field=models.FloatField(default=1),
        ),
        migrations.AddField(
            model_name='systemsetting',
            name='iban_number',
            field=models.CharField(default='TR0100000000000501', max_length=36),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='systemsetting',
            name='swift_number',
            field=models.CharField(default='TR123456', max_length=12),
            preserve_default=False,
        ),
    ]
